version: '3'

tasks:
  default:
    cmds:
      - echo "Welcome to the project! Run 'task --list' to see available tasks."

  build:
    desc: Build the project
    cmds:
      - go build -o bin/go-mail-local cmd/main.go

  run:
    desc: Run the application
    cmds:
      - go run cmd/main.go

  clean:
    desc: Clean up build artifacts
    cmds:
      - rm -rf bin/main