name: Go Mail Local

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: go-mail-local
        path: bin/go-mail-local